### ISSUE TITLE
Interested in this project!

### ISSUE THREAD

**Issue by tspence** [pmdevers/SonarCloud.NET#4]
Hi there!

I wrote my own DotNet SonarCloud integration a little while ago but keep holding out hope for an official one.  I'd love to replace my code with yours and get in sync.

**Comment by tspence** [comment]
A bit of feedback:
* I would like to use the Hotspots API, but the current interface doesn't expose this.  I'll send a PR to add that.
* My goal is to write a tiny headless console application to fetch some data and save it.  Could I suggest we add a tutorial for how to do this to your readme.md page?  Something like this:

```
var sc = new ServiceCollection();
sc.AddSonarCloudClient(cfg => cfg.AccessToken = MY_API_KEY);
var provider = sc.BuildServiceProvider();
var sonarClient = provider.GetService<ISonarCloudApiClient>();
```

**Comment by pmdevers** [comment]
Appreciate the help and all help is welcome.
